[package]
name = "grimmod"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
]
